Repository shreyash3087/The-Last-Bot, pull requests merged in 2025-01, with the labels that each got.

#3 Dragon claw0 patch 2
  Menu.py
Labels: acwoc, medium

#5 Fix: Fixed variable name issue on level 2.
  Assets/Health.txt
  Assets/Score.txt
  Stage2.py
  __pycache__/Final.cpython-313.pyc
  __pycache__/Menu.cpython-313.pyc
  __pycache__/Stage1.cpython-313.pyc
  __pycache__/Stage2.cpython-313.pyc
Labels: acwoc, easy

#7 Added WASD functionality
  Assets/Health.txt
  Assets/Score.txt
  Final.py
  Stage1.py
  Stage2.py
  __pycache__/Stage1.cpython-313.pyc
Labels: acwoc, medium

#10 added an instruction page in the menu
  Instructions.py
  Menu.py
Labels: acwoc, hard
